# This file was generated by GoReleaser. DO NOT EDIT.
cask "gait" do
  version "cli-v0.0.1-rc3"

  on_macos do
    sha256 "00655ab5166049b14ac5f9d7077c44b443aa27fa1527aa499d9ee66c533ece91"
    url "https://github.com/Nstalgic/gait-dist/releases/download/#{version}/gait_darwin_all.tar.gz",
        verified: "github.com/Nstalgic/gait-dist"
  end

  on_linux do
    on_intel do
      sha256 "2c0e65ee4f4a22bae0a27e8160168394369dea4d032c9245670fb0904cc8d178"
      url "https://github.com/Nstalgic/gait-dist/releases/download/#{version}/gait_linux_amd64.tar.gz",
        verified: "github.com/Nstalgic/gait-dist"
    end
    on_arm do
      sha256 "09b715bba5a1b9203155263a031281483485e11e334f5732a82d8060088c033d"
      url "https://github.com/Nstalgic/gait-dist/releases/download/#{version}/gait_linux_arm64.tar.gz",
        verified: "github.com/Nstalgic/gait-dist"
    end
  end

  name "gait"
  desc "A local CI gateway that intercepts git push and runs pipelines locally"
  homepage "https://github.com/Nstalgic/gait-dist"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gait"

  # No zap stanza required

end
