# This file was generated by GoReleaser. DO NOT EDIT.
cask "gait" do
  version "cli-v0.0.1-rc5"

  on_macos do
    sha256 "29bb21212c029dcd8443f4cea7e3060b3f4bb2dcecd32673960cdf924718d524"
    url "https://github.com/Nstalgic/gait-dist/releases/download/#{version}/gait_darwin_all.tar.gz",
        verified: "github.com/Nstalgic/gait-dist"
  end

  on_linux do
    on_intel do
      sha256 "a19bcad13b4d7e07aa27f27fe271e550a3463ca236d3f63e39ecd5e7e5bbdb56"
      url "https://github.com/Nstalgic/gait-dist/releases/download/#{version}/gait_linux_amd64.tar.gz",
        verified: "github.com/Nstalgic/gait-dist"
    end
    on_arm do
      sha256 "2d94b4cd602af5b0e35ba3fce021f0f6d85bf548ddbb1f0ff041066c10020dc4"
      url "https://github.com/Nstalgic/gait-dist/releases/download/#{version}/gait_linux_arm64.tar.gz",
        verified: "github.com/Nstalgic/gait-dist"
    end
  end

  name "gait"
  desc "A local CI gateway that intercepts git push and runs pipelines locally"
  homepage "https://github.com/Nstalgic/gait-dist"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gait"

  # No zap stanza required

end
