# This file was generated by GoReleaser. DO NOT EDIT.
cask "gait" do
  version "cli-v0.0.1-rc2"

  on_macos do
    sha256 "93bc5b013d045b567951a8f5e4228016eff6731773177af33d85f5b6f71bbc9a"
    url "https://github.com/Nstalgic/gait-ci/releases/download/#{version}/gait_darwin_all.tar.gz",
        verified: "github.com/Nstalgic/gait-ci"
  end

  on_linux do
    on_intel do
      sha256 "19ebe84ff57ed4d11b5290b37086d30afc9759f481fe402e1cd2e15af6cae6fd"
      url "https://github.com/Nstalgic/gait-ci/releases/download/#{version}/gait_linux_amd64.tar.gz",
        verified: "github.com/Nstalgic/gait-ci"
    end
    on_arm do
      sha256 "16d75f61fb81c8149a96f9b19621ce09740e63a25989e54310d013fdec9b81a4"
      url "https://github.com/Nstalgic/gait-ci/releases/download/#{version}/gait_linux_arm64.tar.gz",
        verified: "github.com/Nstalgic/gait-ci"
    end
  end

  name "gait"
  desc "A local CI gateway that intercepts git push and runs pipelines locally"
  homepage "https://github.com/Nstalgic/gait-ci"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gait"

  # No zap stanza required

end
